function PlotErrors(X1, YMatrix1, xLbl, legendPosition,exponent)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 10-Nov-2025 13:52:11

% Create figure
figure1 = figure('InvertHardcopy','off','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1.7,'Parent',axes1);
if exponent
axes1.XAxis.Exponent = -4;
end
set(plot1(1),'DisplayName','8-Step PSA $\omega_1=2\omega_0$', 'LineStyle', "-.");
set(plot1(2),'DisplayName','8-Step PSA $\omega_1=3\omega_0$', 'LineStyle', "- -");
set(plot1(3),'DisplayName','12-Step PSA $\omega_1=2\omega_0$', 'LineStyle', "-.");
set(plot1(4),'DisplayName','12-Step PSA $\omega_1=3\omega_0$', 'LineStyle', "- -");
set(plot1(5),'DisplayName','12-Step PSA $\omega_1=4\omega_0$', 'LineStyle', ":");
% $\omega_1=2\omega_0$
% Create ylabel
ylabel('RMSE [mm]','LineWidth',1.7,'FontSize',16,'Interpreter','latex','FontName','Helvetica');

% Create xlabel
xlabel(xLbl,'LineWidth',1.7,'FontSize',16,'Interpreter','latex','FontName','Helvetica');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 8]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 0.15]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',15,'LineWidth',1.7);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location',legendPosition,'LineWidth',1.7,'FontSize',13,'Interpreter','latex','FontName','Helvetica');

