function ShowThreeDimensionalMap(xdata1, zdata1)
%CREATEFIGURE1(xdata1, zdata1)
%  XDATA1:  surface xdata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 25-Feb-2026 15:18:47

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create surf
surf(xdata1,xdata1,zdata1,'Parent',axes1,'LineStyle','none');

% Create zlabel
zlabel('Height [mm]');

% Create ylabel
ylabel('Y Axis [mm]','LineWidth',1.7);

% Create xlabel
xlabel('X Axis [mm]','LineWidth',1.7);

% Create title
title('Three-dimensional map');

view(axes1,[-37.5 30]);
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'DataAspectRatio',[1 1 1],'FontSize',15,'LineWidth',1.7);
